apiVersion: apps/v1
kind: Deployment
metadata:
  name: mopic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mopic
  template:
    metadata:
      labels:
        app: mopic
    spec:
      initContainers:
        - name: chmod-data
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              mkdir /data/qbittorrent && mkdir /data/media && mkdir /data/media/transcoded; \
              chown 1000:1000 /data; \
              chown 1000:1000 /data/media; \
              chown 1000:1000 /data/media/transcoded; \
              chmod 777 /data/media/transcoded; \
              chown 1000:1000 /data/qbittorrent; \

          volumeMounts:
            - name: mopic-data-storage
              mountPath: /data
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: 'PUID'
              value: '1000'
            - name: 'PGID'
              value: '1000'
            - name: 'UMASK'
              value: '002'
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - mountPath: /data
              name: mopic-data-storage
            - mountPath: /config
              name: mopic-radarr-config-storage
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          ports:
            - containerPort: 9696
          env:
            - name: 'PUID'
              value: '1000'
            - name: 'PGID'
              value: '1000'
            - name: 'UMASK'
              value: '002'
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - mountPath: /config
              name: mopic-prowlarr-config-storage
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          ports:
            - containerPort: 5000
          env:
            - name: 'PUID'
              value: '1000'
            - name: 'PGID'
              value: '1000'
            - name: 'UMASK'
              value: '002'
            - name: TZ
              value: Etc/UTC
            - name: WEBUI_PORT
              value: '5000'
            - name: TORRENTING_PORT
              value: '6881'
          volumeMounts:
            - mountPath: /data
              name: mopic-data-storage
            - mountPath: /config
              name: mopic-qbittorrent-config-storage
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          resources:
            requests:
              memory: '8Gi'
              cpu: '2'
            limits:
              memory: '10Gi'
              cpu: '4'
          ports:
            - containerPort: 8096
          env:
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - mountPath: /data
              name: mopic-data-storage
            - mountPath: /config
              name: mopic-jellyfin-config-storage
      volumes:
        - name: mopic-data-storage
          persistentVolumeClaim:
            claimName: mopic-data-storage-claim
        - name: mopic-radarr-config-storage
          persistentVolumeClaim:
            claimName: mopic-radarr-config-storage-claim
        - name: mopic-prowlarr-config-storage
          persistentVolumeClaim:
            claimName: mopic-prowlarr-config-storage-claim
        - name: mopic-qbittorrent-config-storage
          persistentVolumeClaim:
            claimName: mopic-qbittorrent-config-storage-claim
        - name: mopic-jellyfin-config-storage
          persistentVolumeClaim:
            claimName: mopic-jellyfin-config-storage-claim
