apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eks-auto
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: Immediate
reclaimPolicy: Retain
parameters:
  type: gp3
  encrypted: 'true'
