apiVersion: apps/v1
kind: Deployment
metadata:
  name: mopic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mopic
  template:
    metadata:
      labels:
        app: mopic
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: TZ
              value: Etc/UTC
            - name: UMASK
              value: '002'
          volumeMounts:
            - mountPath: /data
              name: mopic-data-storage
            - mountPath: /config
              name: mopic-config-storage
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          ports:
            - containerPort: 9696
          env:
            - name: TZ
              value: Etc/UTC
            - name: UMASK
              value: '002'
          volumeMounts:
            - mountPath: /config
              name: mopic-config-storage
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          ports:
            - containerPort: 5000
          env:
            - name: TZ
              value: Etc/UTC
            - name: UMASK
              value: '002'
            - name: WEBUI_PORT
              value: '5000'
            - name: TORRENTING_PORT
              value: '6881'
          volumeMounts:
            - mountPath: /data
              name: mopic-data-storage
            - mountPath: /config
              name: mopic-config-storage
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
          env:
            - name: UMASK
              value: '002'
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - mountPath: /data
              name: mopic-data-storage
            - mountPath: /config
              name: mopic-config-storage
      volumes:
        - name: mopic-data-storage
          persistentVolumeClaim:
            claimName: mopic-data-storage-claim
        - name: mopic-config-storage
          persistentVolumeClaim:
            claimName: mopic-config-storage-claim
