apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-radarr-config-storage-claim
spec:
  storageClassName: 'aws-ebs' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-prowlarr-config-storage-claim
spec:
  storageClassName: 'aws-ebs' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-qbittorrent-config-storage-claim
spec:
  storageClassName: 'aws-ebs' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-jellyfin-config-storage-claim
spec:
  storageClassName: 'aws-ebs' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-data-storage-claim
spec:
  storageClassName: 'aws-ebs' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
