apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-radarr-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 'eks-auto'
  claimRef:
    namespace: default
    name: mopic-radarr-config-storage-claim
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-0e0200b81b8313e3f

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-prowlarr-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 'eks-auto'
  claimRef:
    namespace: default
    name: mopic-prowlarr-config-storage-claim
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-068f78a5d4af0d028

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-qbittorrent-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mopic-qbittorrent-config-storage-claim
  storageClassName: 'eks-auto'
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-05ededce02e40b02c

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-jellyfin-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mopic-jellyfin-config-storage-claim
  storageClassName: 'eks-auto'
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-0bb57b53a1d501557

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-data-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 'eks-auto'
  claimRef:
    namespace: default
    name: mopic-data-storage-claim
  capacity:
    storage: 500Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-0ea419c9bb5e71bbd
