apiVersion: v1
kind: Service
metadata:
  name: mopic-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: qbittorrent
    - port: 8081
      targetPort: 7878
      protocol: TCP
      name: radarr
    - port: 8082
      targetPort: 9696
      protocol: TCP
      name: prowlarr
    - port: 8083
      targetPort: 8096
      protocol: TCP
      name: jellyfin
  type: NodePort
  selector:
    app: mopic

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mopic-ingress
  annotations:
    alb.ingress.kubernetes.io/target-type: instance
  labels:
    app: mopic
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: mopic-service
                port:
                  name: jellyfin
          # - pathType: Prefix
          #   path: '/'
          #   backend:
          #     service:
          #       name: mopic-service
          #       port:
          #         name: radarr
          # - pathType: Prefix
          #   path: '/'
          #   backend:
          #     service:
          #       name: mopic-service
          #       port:
          #         name: radarr
          # - pathType: Prefix
          #   path: '/'
          #   backend:
          #     service:
          #       name: mopic-service
          #       port:
          #         name: radarr
