apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-radarr-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f41

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-prowlarr-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f42

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-qbittorrent-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f43

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-jellyfin-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f44

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-data-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  csi:
    driver: ebs.csi.eks.amazonaws.com
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f45
