apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-data-storage
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  # mountOptions:
  #   - allow-delete
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mopic-data # Must be unique
    volumeAttributes:
      bucketName: mopic-data
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: mopic-data-storage-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-config-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  # mountOptions:
  #   - allow-delete
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mopic-config # Must be unique
    volumeAttributes:
      bucketName: mopic-config
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: mopic-config-storage-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-data-storage-claim
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: '' # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi # Ignored, required
  volumeName: mopic-data-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-config-storage-claim
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: '' # Required for static provisioning
  resources:
    requests:
      storage: 1Gi # Ignored, required
  volumeName: mopic-config-storage
