apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-radarr-data-storage
spec:
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  mountOptions:
    - allow-delete
    - allow-overwrite
    - allow-root
    - prefix /mopic/data/
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mopic-data # Must be unique
    volumeAttributes:
      bucketName: mopic-data
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: mopic-radarr-data-storage-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-jellyfin-data-storage
spec:
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  mountOptions:
    - allow-delete
    - allow-overwrite
    - allow-root
    - prefix /mopic/data/media/
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mopic-data # Must be unique
    volumeAttributes:
      bucketName: mopic-data
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: mopic-jellyfin-data-storage-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-qbittorrent-data-storage
spec:
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  mountOptions:
    - allow-delete
    - allow-overwrite
    - allow-root
    - prefix /mopic/data/qbittorrent/
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mopic-data # Must be unique
    volumeAttributes:
      bucketName: mopic-data
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: mopic-qbittorrent-data-storage-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-radarr-config-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  mountOptions:
    - allow-delete
    - allow-overwrite
    - allow-root
    - prefix /mopic/config/radarr/
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mopic-config # Must be unique
    volumeAttributes:
      bucketName: mopic-config
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: mopic-radarr-config-storage-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-prowlarr-config-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  mountOptions:
    - allow-delete
    - allow-overwrite
    - allow-root
    - prefix /mopic/config/prowlarr/
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mopic-config # Must be unique
    volumeAttributes:
      bucketName: mopic-config
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: mopic-prowlarr-config-storage-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopic-qbittorrent-config-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  mountOptions:
    - allow-delete
    - allow-overwrite
    - allow-root
    - prefix /mopic/config/qbittorrent/
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mopic-config # Must be unique
    volumeAttributes:
      bucketName: mopic-config
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: mopic-qbittorrent-config-storage-claim
