apiVersion: apps/v1
kind: Deployment
metadata:
  name: mopic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mopic
  template:
    metadata:
      labels:
        app: mopic
    spec:
      restartPolicy: OnFailure
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
            - name: UMASK
              value: '002'
          volumeMounts:
            - mountPath: /data
              name: mopic_data_storage
            - mountPath: /config/radarr
              name: mopic_config_storage
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
            - name: UMASK
              value: '002'
          volumeMounts:
            - mountPath: /config/prowlarr
              name: mopic_config_storage
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          ports:
            - containerPort: 5000
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
            - name: UMASK
              value: '002'
            - name: WEBUI_PORT
              value: '5000/TCP'
            - name: TORRENTING_PORT
              value: '6881'
          volumeMounts:
            - mountPath: /data/qbittorents
              name: mopic_data_storage
            - mountPath: /config
              name: mopic_config_storage
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: UMASK
              value: '002'
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - mountPath: /data/media
              name: mopic_data_storage
            - mountPath: /config
              name: mopic_config_storage
      volumes:
        - name: mopic_data_storage
          persistentVolumeClaim:
            claimName: mopic_data_storage_claim
        - name: mopic_config_storage
          persistentVolumeClaim:
            claimName: mopic_config_storage_claim
