apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: config-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3
  throughput: '700'
  iops: '500'
