apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-radarr-config-storage-claim
spec:
  storageClassName: 'config-storage-class' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: mopic-snapshot-radarr-config
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-prowlarr-config-storage-claim
spec:
  storageClassName: 'config-storage-class' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: mopic-snapshot-prowlarr-config
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-qbittorrent-config-storage-claim
spec:
  storageClassName: 'config-storage-class' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: mopic-snapshot-qbittorrent-config
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-jellyfin-config-storage-claim
spec:
  storageClassName: 'config-storage-class' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: mopic-snapshot-jellyfin-config
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopic-data-storage-claim
spec:
  storageClassName: 'media-storage-class' # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
