apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: io2
  iops: '64000'
